pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
    }
}
rootProject.name = "FlymeNotifyIconFix"
include ':app'
